max_winners: 3
metadata_endpoint: https://api.mutantdao.com/hounds/metadata
etherscan_rate_limit: 4
snapshot: 
    start: 2023-04-02T00:00:00Z #RC3339 YY-MM-DDTHH:MM:SS
    stop:  2023-04-03T16:00:00Z #RC3339 YY-MM-DDTHH:MM:SS
ineligible_traits:
   forms: 
       - Fire 
       - Icy 
       - Diamond
       - Gold 
       - Trippy 
       - Trippy 2
       - Noise
       - Dragon

   faces: 
       - Orange Smoke
       - Blue Beams
       - Laser Eyes
       - Ghost Eyes
       - Demon Eyes
       - Ghost Eyes

   mouths:
       - Orange Flame
       - Death Ray
       - Blue Beam
       - Blue Flame
       - Serum Laser
   
   torsos:
       - Demon Wings
       - Angel Wings
       - Dragon Wings
       - Tiger Saddle
       - Mutant Saddle
       - Jet Pack
       - Ritual Robe
       - Golden Angel Wings
